// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// CreateGroupOKCode is the HTTP code returned for type CreateGroupOK
const CreateGroupOKCode int = 200

/*CreateGroupOK The new gorup.

swagger:response createGroupOK
*/
type CreateGroupOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Group `json:"body,omitempty"`
}

// NewCreateGroupOK creates CreateGroupOK with default headers values
func NewCreateGroupOK() *CreateGroupOK {

	return &CreateGroupOK{}
}

// WithPayload adds the payload to the create group o k response
func (o *CreateGroupOK) WithPayload(payload *modelapi.Group) *CreateGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create group o k response
func (o *CreateGroupOK) SetPayload(payload *modelapi.Group) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateGroupBadRequestCode is the HTTP code returned for type CreateGroupBadRequest
const CreateGroupBadRequestCode int = 400

/*CreateGroupBadRequest Supplied parameters were not okay.

swagger:response createGroupBadRequest
*/
type CreateGroupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewCreateGroupBadRequest creates CreateGroupBadRequest with default headers values
func NewCreateGroupBadRequest() *CreateGroupBadRequest {

	return &CreateGroupBadRequest{}
}

// WithPayload adds the payload to the create group bad request response
func (o *CreateGroupBadRequest) WithPayload(payload *modelapi.Error) *CreateGroupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create group bad request response
func (o *CreateGroupBadRequest) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGroupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateGroupUnauthorizedCode is the HTTP code returned for type CreateGroupUnauthorized
const CreateGroupUnauthorizedCode int = 401

/*CreateGroupUnauthorized Unauthorized.

swagger:response createGroupUnauthorized
*/
type CreateGroupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewCreateGroupUnauthorized creates CreateGroupUnauthorized with default headers values
func NewCreateGroupUnauthorized() *CreateGroupUnauthorized {

	return &CreateGroupUnauthorized{}
}

// WithPayload adds the payload to the create group unauthorized response
func (o *CreateGroupUnauthorized) WithPayload(payload *modelapi.Error) *CreateGroupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create group unauthorized response
func (o *CreateGroupUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateGroupInternalServerErrorCode is the HTTP code returned for type CreateGroupInternalServerError
const CreateGroupInternalServerErrorCode int = 500

/*CreateGroupInternalServerError Internal server error.

swagger:response createGroupInternalServerError
*/
type CreateGroupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewCreateGroupInternalServerError creates CreateGroupInternalServerError with default headers values
func NewCreateGroupInternalServerError() *CreateGroupInternalServerError {

	return &CreateGroupInternalServerError{}
}

// WithPayload adds the payload to the create group internal server error response
func (o *CreateGroupInternalServerError) WithPayload(payload *modelapi.Error) *CreateGroupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create group internal server error response
func (o *CreateGroupInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateGroupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
