// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetGroupMembersOKCode is the HTTP code returned for type GetGroupMembersOK
const GetGroupMembersOKCode int = 200

/*GetGroupMembersOK Array of group members.

swagger:response getGroupMembersOK
*/
type GetGroupMembersOK struct {

	/*
	  In: Body
	*/
	Payload []*modelapi.User `json:"body,omitempty"`
}

// NewGetGroupMembersOK creates GetGroupMembersOK with default headers values
func NewGetGroupMembersOK() *GetGroupMembersOK {

	return &GetGroupMembersOK{}
}

// WithPayload adds the payload to the get group members o k response
func (o *GetGroupMembersOK) WithPayload(payload []*modelapi.User) *GetGroupMembersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group members o k response
func (o *GetGroupMembersOK) SetPayload(payload []*modelapi.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupMembersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*modelapi.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetGroupMembersBadRequestCode is the HTTP code returned for type GetGroupMembersBadRequest
const GetGroupMembersBadRequestCode int = 400

/*GetGroupMembersBadRequest Supplied parameters were not okay.

swagger:response getGroupMembersBadRequest
*/
type GetGroupMembersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupMembersBadRequest creates GetGroupMembersBadRequest with default headers values
func NewGetGroupMembersBadRequest() *GetGroupMembersBadRequest {

	return &GetGroupMembersBadRequest{}
}

// WithPayload adds the payload to the get group members bad request response
func (o *GetGroupMembersBadRequest) WithPayload(payload *modelapi.Error) *GetGroupMembersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group members bad request response
func (o *GetGroupMembersBadRequest) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupMembersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupMembersUnauthorizedCode is the HTTP code returned for type GetGroupMembersUnauthorized
const GetGroupMembersUnauthorizedCode int = 401

/*GetGroupMembersUnauthorized Unauthorized.

swagger:response getGroupMembersUnauthorized
*/
type GetGroupMembersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupMembersUnauthorized creates GetGroupMembersUnauthorized with default headers values
func NewGetGroupMembersUnauthorized() *GetGroupMembersUnauthorized {

	return &GetGroupMembersUnauthorized{}
}

// WithPayload adds the payload to the get group members unauthorized response
func (o *GetGroupMembersUnauthorized) WithPayload(payload *modelapi.Error) *GetGroupMembersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group members unauthorized response
func (o *GetGroupMembersUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupMembersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupMembersInternalServerErrorCode is the HTTP code returned for type GetGroupMembersInternalServerError
const GetGroupMembersInternalServerErrorCode int = 500

/*GetGroupMembersInternalServerError Internal server error.

swagger:response getGroupMembersInternalServerError
*/
type GetGroupMembersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupMembersInternalServerError creates GetGroupMembersInternalServerError with default headers values
func NewGetGroupMembersInternalServerError() *GetGroupMembersInternalServerError {

	return &GetGroupMembersInternalServerError{}
}

// WithPayload adds the payload to the get group members internal server error response
func (o *GetGroupMembersInternalServerError) WithPayload(payload *modelapi.Error) *GetGroupMembersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group members internal server error response
func (o *GetGroupMembersInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupMembersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
