// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetGroupInvitesOKCode is the HTTP code returned for type GetGroupInvitesOK
const GetGroupInvitesOKCode int = 200

/*GetGroupInvitesOK Array of active invites of the group.

swagger:response getGroupInvitesOK
*/
type GetGroupInvitesOK struct {

	/*
	  In: Body
	*/
	Payload []*modelapi.Invite `json:"body,omitempty"`
}

// NewGetGroupInvitesOK creates GetGroupInvitesOK with default headers values
func NewGetGroupInvitesOK() *GetGroupInvitesOK {

	return &GetGroupInvitesOK{}
}

// WithPayload adds the payload to the get group invites o k response
func (o *GetGroupInvitesOK) WithPayload(payload []*modelapi.Invite) *GetGroupInvitesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group invites o k response
func (o *GetGroupInvitesOK) SetPayload(payload []*modelapi.Invite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupInvitesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*modelapi.Invite, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetGroupInvitesUnauthorizedCode is the HTTP code returned for type GetGroupInvitesUnauthorized
const GetGroupInvitesUnauthorizedCode int = 401

/*GetGroupInvitesUnauthorized Unauthorized.

swagger:response getGroupInvitesUnauthorized
*/
type GetGroupInvitesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupInvitesUnauthorized creates GetGroupInvitesUnauthorized with default headers values
func NewGetGroupInvitesUnauthorized() *GetGroupInvitesUnauthorized {

	return &GetGroupInvitesUnauthorized{}
}

// WithPayload adds the payload to the get group invites unauthorized response
func (o *GetGroupInvitesUnauthorized) WithPayload(payload *modelapi.Error) *GetGroupInvitesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group invites unauthorized response
func (o *GetGroupInvitesUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupInvitesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
