// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGroupInvitesHandlerFunc turns a function with the right signature into a get group invites handler
type GetGroupInvitesHandlerFunc func(GetGroupInvitesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGroupInvitesHandlerFunc) Handle(params GetGroupInvitesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGroupInvitesHandler interface for that can handle valid get group invites params
type GetGroupInvitesHandler interface {
	Handle(GetGroupInvitesParams, interface{}) middleware.Responder
}

// NewGetGroupInvites creates a new http.Handler for the get group invites operation
func NewGetGroupInvites(ctx *middleware.Context, handler GetGroupInvitesHandler) *GetGroupInvites {
	return &GetGroupInvites{Context: ctx, Handler: handler}
}

/* GetGroupInvites swagger:route GET /users/current/groups/{group_id}/invites group getGroupInvites

Get active invites of a group

*/
type GetGroupInvites struct {
	Context *middleware.Context
	Handler GetGroupInvitesHandler
}

func (o *GetGroupInvites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGroupInvitesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
