// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// InviteUserToGroupOKCode is the HTTP code returned for type InviteUserToGroupOK
const InviteUserToGroupOKCode int = 200

/*InviteUserToGroupOK The newly created invite object.

swagger:response inviteUserToGroupOK
*/
type InviteUserToGroupOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Invite `json:"body,omitempty"`
}

// NewInviteUserToGroupOK creates InviteUserToGroupOK with default headers values
func NewInviteUserToGroupOK() *InviteUserToGroupOK {

	return &InviteUserToGroupOK{}
}

// WithPayload adds the payload to the invite user to group o k response
func (o *InviteUserToGroupOK) WithPayload(payload *modelapi.Invite) *InviteUserToGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invite user to group o k response
func (o *InviteUserToGroupOK) SetPayload(payload *modelapi.Invite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InviteUserToGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InviteUserToGroupBadRequestCode is the HTTP code returned for type InviteUserToGroupBadRequest
const InviteUserToGroupBadRequestCode int = 400

/*InviteUserToGroupBadRequest Supplied parameters were not okay.

swagger:response inviteUserToGroupBadRequest
*/
type InviteUserToGroupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewInviteUserToGroupBadRequest creates InviteUserToGroupBadRequest with default headers values
func NewInviteUserToGroupBadRequest() *InviteUserToGroupBadRequest {

	return &InviteUserToGroupBadRequest{}
}

// WithPayload adds the payload to the invite user to group bad request response
func (o *InviteUserToGroupBadRequest) WithPayload(payload *modelapi.Error) *InviteUserToGroupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invite user to group bad request response
func (o *InviteUserToGroupBadRequest) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InviteUserToGroupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InviteUserToGroupUnauthorizedCode is the HTTP code returned for type InviteUserToGroupUnauthorized
const InviteUserToGroupUnauthorizedCode int = 401

/*InviteUserToGroupUnauthorized Unauthorized.

swagger:response inviteUserToGroupUnauthorized
*/
type InviteUserToGroupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewInviteUserToGroupUnauthorized creates InviteUserToGroupUnauthorized with default headers values
func NewInviteUserToGroupUnauthorized() *InviteUserToGroupUnauthorized {

	return &InviteUserToGroupUnauthorized{}
}

// WithPayload adds the payload to the invite user to group unauthorized response
func (o *InviteUserToGroupUnauthorized) WithPayload(payload *modelapi.Error) *InviteUserToGroupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invite user to group unauthorized response
func (o *InviteUserToGroupUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InviteUserToGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
