root = "."
testdata_dir = "testdata"
tmp_dir = "./air/tmp"

[build]
  bin = "air\\tmp\\main.exe"
  args_bin = ["--port 1000"]
  cmd = "go build -o ./air/tmp/main.exe ./cmd/mnimidamon-server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true
