// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// DeleteComputerNoContentCode is the HTTP code returned for type DeleteComputerNoContent
const DeleteComputerNoContentCode int = 204

/*DeleteComputerNoContent Computer succesfully deleted

swagger:response deleteComputerNoContent
*/
type DeleteComputerNoContent struct {
}

// NewDeleteComputerNoContent creates DeleteComputerNoContent with default headers values
func NewDeleteComputerNoContent() *DeleteComputerNoContent {

	return &DeleteComputerNoContent{}
}

// WriteResponse to the client
func (o *DeleteComputerNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteComputerBadRequestCode is the HTTP code returned for type DeleteComputerBadRequest
const DeleteComputerBadRequestCode int = 400

/*DeleteComputerBadRequest Supplied parameters were not okay.

swagger:response deleteComputerBadRequest
*/
type DeleteComputerBadRequest struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewDeleteComputerBadRequest creates DeleteComputerBadRequest with default headers values
func NewDeleteComputerBadRequest() *DeleteComputerBadRequest {

	return &DeleteComputerBadRequest{}
}

// WithPayload adds the payload to the delete computer bad request response
func (o *DeleteComputerBadRequest) WithPayload(payload *modelapi.Error) *DeleteComputerBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete computer bad request response
func (o *DeleteComputerBadRequest) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteComputerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteComputerUnauthorizedCode is the HTTP code returned for type DeleteComputerUnauthorized
const DeleteComputerUnauthorizedCode int = 401

/*DeleteComputerUnauthorized Unauthorized.

swagger:response deleteComputerUnauthorized
*/
type DeleteComputerUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewDeleteComputerUnauthorized creates DeleteComputerUnauthorized with default headers values
func NewDeleteComputerUnauthorized() *DeleteComputerUnauthorized {

	return &DeleteComputerUnauthorized{}
}

// WithPayload adds the payload to the delete computer unauthorized response
func (o *DeleteComputerUnauthorized) WithPayload(payload *modelapi.Error) *DeleteComputerUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete computer unauthorized response
func (o *DeleteComputerUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteComputerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteComputerInternalServerErrorCode is the HTTP code returned for type DeleteComputerInternalServerError
const DeleteComputerInternalServerErrorCode int = 500

/*DeleteComputerInternalServerError Internal server error.

swagger:response deleteComputerInternalServerError
*/
type DeleteComputerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewDeleteComputerInternalServerError creates DeleteComputerInternalServerError with default headers values
func NewDeleteComputerInternalServerError() *DeleteComputerInternalServerError {

	return &DeleteComputerInternalServerError{}
}

// WithPayload adds the payload to the delete computer internal server error response
func (o *DeleteComputerInternalServerError) WithPayload(payload *modelapi.Error) *DeleteComputerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete computer internal server error response
func (o *DeleteComputerInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteComputerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
