// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCurrentComputerHandlerFunc turns a function with the right signature into a get current computer handler
type GetCurrentComputerHandlerFunc func(GetCurrentComputerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCurrentComputerHandlerFunc) Handle(params GetCurrentComputerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCurrentComputerHandler interface for that can handle valid get current computer params
type GetCurrentComputerHandler interface {
	Handle(GetCurrentComputerParams, interface{}) middleware.Responder
}

// NewGetCurrentComputer creates a new http.Handler for the get current computer operation
func NewGetCurrentComputer(ctx *middleware.Context, handler GetCurrentComputerHandler) *GetCurrentComputer {
	return &GetCurrentComputer{Context: ctx, Handler: handler}
}

/* GetCurrentComputer swagger:route GET /users/current/computers/current computer getCurrentComputer

Get current computer

*/
type GetCurrentComputer struct {
	Context *middleware.Context
	Handler GetCurrentComputerHandler
}

func (o *GetCurrentComputer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCurrentComputerParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
