// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetCurrentComputerOKCode is the HTTP code returned for type GetCurrentComputerOK
const GetCurrentComputerOKCode int = 200

/*GetCurrentComputerOK The current Computer.

swagger:response getCurrentComputerOK
*/
type GetCurrentComputerOK struct {

	/*
	  In: Body
	*/
	Payload []*modelapi.Computer `json:"body,omitempty"`
}

// NewGetCurrentComputerOK creates GetCurrentComputerOK with default headers values
func NewGetCurrentComputerOK() *GetCurrentComputerOK {

	return &GetCurrentComputerOK{}
}

// WithPayload adds the payload to the get current computer o k response
func (o *GetCurrentComputerOK) WithPayload(payload []*modelapi.Computer) *GetCurrentComputerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current computer o k response
func (o *GetCurrentComputerOK) SetPayload(payload []*modelapi.Computer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentComputerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*modelapi.Computer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCurrentComputerUnauthorizedCode is the HTTP code returned for type GetCurrentComputerUnauthorized
const GetCurrentComputerUnauthorizedCode int = 401

/*GetCurrentComputerUnauthorized Unauthorized.

swagger:response getCurrentComputerUnauthorized
*/
type GetCurrentComputerUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetCurrentComputerUnauthorized creates GetCurrentComputerUnauthorized with default headers values
func NewGetCurrentComputerUnauthorized() *GetCurrentComputerUnauthorized {

	return &GetCurrentComputerUnauthorized{}
}

// WithPayload adds the payload to the get current computer unauthorized response
func (o *GetCurrentComputerUnauthorized) WithPayload(payload *modelapi.Error) *GetCurrentComputerUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current computer unauthorized response
func (o *GetCurrentComputerUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentComputerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCurrentComputerInternalServerErrorCode is the HTTP code returned for type GetCurrentComputerInternalServerError
const GetCurrentComputerInternalServerErrorCode int = 500

/*GetCurrentComputerInternalServerError Internal server error.

swagger:response getCurrentComputerInternalServerError
*/
type GetCurrentComputerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetCurrentComputerInternalServerError creates GetCurrentComputerInternalServerError with default headers values
func NewGetCurrentComputerInternalServerError() *GetCurrentComputerInternalServerError {

	return &GetCurrentComputerInternalServerError{}
}

// WithPayload adds the payload to the get current computer internal server error response
func (o *GetCurrentComputerInternalServerError) WithPayload(payload *modelapi.Error) *GetCurrentComputerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current computer internal server error response
func (o *GetCurrentComputerInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentComputerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
