// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetCurrentUserComputerOKCode is the HTTP code returned for type GetCurrentUserComputerOK
const GetCurrentUserComputerOKCode int = 200

/*GetCurrentUserComputerOK The computer

swagger:response getCurrentUserComputerOK
*/
type GetCurrentUserComputerOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Computer `json:"body,omitempty"`
}

// NewGetCurrentUserComputerOK creates GetCurrentUserComputerOK with default headers values
func NewGetCurrentUserComputerOK() *GetCurrentUserComputerOK {

	return &GetCurrentUserComputerOK{}
}

// WithPayload adds the payload to the get current user computer o k response
func (o *GetCurrentUserComputerOK) WithPayload(payload *modelapi.Computer) *GetCurrentUserComputerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user computer o k response
func (o *GetCurrentUserComputerOK) SetPayload(payload *modelapi.Computer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserComputerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCurrentUserComputerUnauthorizedCode is the HTTP code returned for type GetCurrentUserComputerUnauthorized
const GetCurrentUserComputerUnauthorizedCode int = 401

/*GetCurrentUserComputerUnauthorized Unauthorized.

swagger:response getCurrentUserComputerUnauthorized
*/
type GetCurrentUserComputerUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetCurrentUserComputerUnauthorized creates GetCurrentUserComputerUnauthorized with default headers values
func NewGetCurrentUserComputerUnauthorized() *GetCurrentUserComputerUnauthorized {

	return &GetCurrentUserComputerUnauthorized{}
}

// WithPayload adds the payload to the get current user computer unauthorized response
func (o *GetCurrentUserComputerUnauthorized) WithPayload(payload *modelapi.Error) *GetCurrentUserComputerUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user computer unauthorized response
func (o *GetCurrentUserComputerUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserComputerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
