// Code generated by go-swagger; DO NOT EDIT.

// Package endpoints mnimidamon server
//
//  This is OpenAPI specification for Mnimidamon backend, cross platform application for file backups.
//  Schemes:
//    http
//  Host: mnimidamon.marmiha.com
//  BasePath: /api/v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <miha.markez@gmail.com>
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package endpoints
