// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewDeleteCurrentUserParams creates a new DeleteCurrentUserParams object
//
// There are no default values defined in the spec.
func NewDeleteCurrentUserParams() DeleteCurrentUserParams {

	return DeleteCurrentUserParams{}
}

// DeleteCurrentUserParams contains all the bound params for the delete current user operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteCurrentUser
type DeleteCurrentUserParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteCurrentUserParams() beforehand.
func (o *DeleteCurrentUserParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
