// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// InviteUserToGroupHandlerFunc turns a function with the right signature into a invite user to group handler
type InviteUserToGroupHandlerFunc func(InviteUserToGroupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn InviteUserToGroupHandlerFunc) Handle(params InviteUserToGroupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// InviteUserToGroupHandler interface for that can handle valid invite user to group params
type InviteUserToGroupHandler interface {
	Handle(InviteUserToGroupParams, interface{}) middleware.Responder
}

// NewInviteUserToGroup creates a new http.Handler for the invite user to group operation
func NewInviteUserToGroup(ctx *middleware.Context, handler InviteUserToGroupHandler) *InviteUserToGroup {
	return &InviteUserToGroup{Context: ctx, Handler: handler}
}

/* InviteUserToGroup swagger:route POST /users/current/groups/{group_id}/invites group inviteUserToGroup

Invite an user to a group

*/
type InviteUserToGroup struct {
	Context *middleware.Context
	Handler InviteUserToGroupHandler
}

func (o *InviteUserToGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInviteUserToGroupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
