// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/models"
)

// InviteUserToGroupOKCode is the HTTP code returned for type InviteUserToGroupOK
const InviteUserToGroupOKCode int = 200

/*InviteUserToGroupOK The newly created invite object.

swagger:response inviteUserToGroupOK
*/
type InviteUserToGroupOK struct {

	/*
	  In: Body
	*/
	Payload *models.Invite `json:"body,omitempty"`
}

// NewInviteUserToGroupOK creates InviteUserToGroupOK with default headers values
func NewInviteUserToGroupOK() *InviteUserToGroupOK {

	return &InviteUserToGroupOK{}
}

// WithPayload adds the payload to the invite user to group o k response
func (o *InviteUserToGroupOK) WithPayload(payload *models.Invite) *InviteUserToGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invite user to group o k response
func (o *InviteUserToGroupOK) SetPayload(payload *models.Invite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InviteUserToGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InviteUserToGroupUnauthorizedCode is the HTTP code returned for type InviteUserToGroupUnauthorized
const InviteUserToGroupUnauthorizedCode int = 401

/*InviteUserToGroupUnauthorized Unauthorized.

swagger:response inviteUserToGroupUnauthorized
*/
type InviteUserToGroupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewInviteUserToGroupUnauthorized creates InviteUserToGroupUnauthorized with default headers values
func NewInviteUserToGroupUnauthorized() *InviteUserToGroupUnauthorized {

	return &InviteUserToGroupUnauthorized{}
}

// WithPayload adds the payload to the invite user to group unauthorized response
func (o *InviteUserToGroupUnauthorized) WithPayload(payload *models.Error) *InviteUserToGroupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invite user to group unauthorized response
func (o *InviteUserToGroupUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InviteUserToGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InviteUserToGroupNotFoundCode is the HTTP code returned for type InviteUserToGroupNotFound
const InviteUserToGroupNotFoundCode int = 404

/*InviteUserToGroupNotFound Supplied parameters were not okay.

swagger:response inviteUserToGroupNotFound
*/
type InviteUserToGroupNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewInviteUserToGroupNotFound creates InviteUserToGroupNotFound with default headers values
func NewInviteUserToGroupNotFound() *InviteUserToGroupNotFound {

	return &InviteUserToGroupNotFound{}
}

// WithPayload adds the payload to the invite user to group not found response
func (o *InviteUserToGroupNotFound) WithPayload(payload *models.Error) *InviteUserToGroupNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invite user to group not found response
func (o *InviteUserToGroupNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InviteUserToGroupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
