// Code generated by go-swagger; DO NOT EDIT.

package group_computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// JoinComputerToGroupURL generates an URL for the join computer to group operation
type JoinComputerToGroupURL struct {
	GroupID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *JoinComputerToGroupURL) WithBasePath(bp string) *JoinComputerToGroupURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *JoinComputerToGroupURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *JoinComputerToGroupURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/users/current/computers/current/groups/{group_id}/join"

	groupID := swag.FormatInt64(o.GroupID)
	if groupID != "" {
		_path = strings.Replace(_path, "{group_id}", groupID, -1)
	} else {
		return nil, errors.New("groupId is required on JoinComputerToGroupURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *JoinComputerToGroupURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *JoinComputerToGroupURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *JoinComputerToGroupURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on JoinComputerToGroupURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on JoinComputerToGroupURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *JoinComputerToGroupURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
