// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RegisterComputerHandlerFunc turns a function with the right signature into a register computer handler
type RegisterComputerHandlerFunc func(RegisterComputerParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterComputerHandlerFunc) Handle(params RegisterComputerParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RegisterComputerHandler interface for that can handle valid register computer params
type RegisterComputerHandler interface {
	Handle(RegisterComputerParams, interface{}) middleware.Responder
}

// NewRegisterComputer creates a new http.Handler for the register computer operation
func NewRegisterComputer(ctx *middleware.Context, handler RegisterComputerHandler) *RegisterComputer {
	return &RegisterComputer{Context: ctx, Handler: handler}
}

/* RegisterComputer swagger:route POST /users/current/computers authorization computer registerComputer

Create a computer and get the computer api key

*/
type RegisterComputer struct {
	Context *middleware.Context
	Handler RegisterComputerHandler
}

func (o *RegisterComputer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterComputerParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
