// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCurrentUserComputersHandlerFunc turns a function with the right signature into a get current user computers handler
type GetCurrentUserComputersHandlerFunc func(GetCurrentUserComputersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCurrentUserComputersHandlerFunc) Handle(params GetCurrentUserComputersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCurrentUserComputersHandler interface for that can handle valid get current user computers params
type GetCurrentUserComputersHandler interface {
	Handle(GetCurrentUserComputersParams, interface{}) middleware.Responder
}

// NewGetCurrentUserComputers creates a new http.Handler for the get current user computers operation
func NewGetCurrentUserComputers(ctx *middleware.Context, handler GetCurrentUserComputersHandler) *GetCurrentUserComputers {
	return &GetCurrentUserComputers{Context: ctx, Handler: handler}
}

/* GetCurrentUserComputers swagger:route GET /users/current/computers computer getCurrentUserComputers

Get all computer of the current user

*/
type GetCurrentUserComputers struct {
	Context *middleware.Context
	Handler GetCurrentUserComputersHandler
}

func (o *GetCurrentUserComputers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCurrentUserComputersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
