// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/models"
)

// GetCurrentUserComputersOKCode is the HTTP code returned for type GetCurrentUserComputersOK
const GetCurrentUserComputersOKCode int = 200

/*GetCurrentUserComputersOK Current user computers

swagger:response getCurrentUserComputersOK
*/
type GetCurrentUserComputersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Computer `json:"body,omitempty"`
}

// NewGetCurrentUserComputersOK creates GetCurrentUserComputersOK with default headers values
func NewGetCurrentUserComputersOK() *GetCurrentUserComputersOK {

	return &GetCurrentUserComputersOK{}
}

// WithPayload adds the payload to the get current user computers o k response
func (o *GetCurrentUserComputersOK) WithPayload(payload []*models.Computer) *GetCurrentUserComputersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user computers o k response
func (o *GetCurrentUserComputersOK) SetPayload(payload []*models.Computer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserComputersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Computer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCurrentUserComputersUnauthorizedCode is the HTTP code returned for type GetCurrentUserComputersUnauthorized
const GetCurrentUserComputersUnauthorizedCode int = 401

/*GetCurrentUserComputersUnauthorized Unauthorized.

swagger:response getCurrentUserComputersUnauthorized
*/
type GetCurrentUserComputersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCurrentUserComputersUnauthorized creates GetCurrentUserComputersUnauthorized with default headers values
func NewGetCurrentUserComputersUnauthorized() *GetCurrentUserComputersUnauthorized {

	return &GetCurrentUserComputersUnauthorized{}
}

// WithPayload adds the payload to the get current user computers unauthorized response
func (o *GetCurrentUserComputersUnauthorized) WithPayload(payload *models.Error) *GetCurrentUserComputersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user computers unauthorized response
func (o *GetCurrentUserComputersUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserComputersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
