// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeclineCurrentUserInviteHandlerFunc turns a function with the right signature into a decline current user invite handler
type DeclineCurrentUserInviteHandlerFunc func(DeclineCurrentUserInviteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeclineCurrentUserInviteHandlerFunc) Handle(params DeclineCurrentUserInviteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeclineCurrentUserInviteHandler interface for that can handle valid decline current user invite params
type DeclineCurrentUserInviteHandler interface {
	Handle(DeclineCurrentUserInviteParams, interface{}) middleware.Responder
}

// NewDeclineCurrentUserInvite creates a new http.Handler for the decline current user invite operation
func NewDeclineCurrentUserInvite(ctx *middleware.Context, handler DeclineCurrentUserInviteHandler) *DeclineCurrentUserInvite {
	return &DeclineCurrentUserInvite{Context: ctx, Handler: handler}
}

/* DeclineCurrentUserInvite swagger:route DELETE /users/current/invites/{group_id} invite declineCurrentUserInvite

Decline a group invite

*/
type DeclineCurrentUserInvite struct {
	Context *middleware.Context
	Handler DeclineCurrentUserInviteHandler
}

func (o *DeclineCurrentUserInvite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeclineCurrentUserInviteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
