// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetCurrentUserInviteOKCode is the HTTP code returned for type GetCurrentUserInviteOK
const GetCurrentUserInviteOKCode int = 200

/*GetCurrentUserInviteOK Invite object

swagger:response getCurrentUserInviteOK
*/
type GetCurrentUserInviteOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Invite `json:"body,omitempty"`
}

// NewGetCurrentUserInviteOK creates GetCurrentUserInviteOK with default headers values
func NewGetCurrentUserInviteOK() *GetCurrentUserInviteOK {

	return &GetCurrentUserInviteOK{}
}

// WithPayload adds the payload to the get current user invite o k response
func (o *GetCurrentUserInviteOK) WithPayload(payload *modelapi.Invite) *GetCurrentUserInviteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user invite o k response
func (o *GetCurrentUserInviteOK) SetPayload(payload *modelapi.Invite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserInviteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCurrentUserInviteUnauthorizedCode is the HTTP code returned for type GetCurrentUserInviteUnauthorized
const GetCurrentUserInviteUnauthorizedCode int = 401

/*GetCurrentUserInviteUnauthorized Unauthorized.

swagger:response getCurrentUserInviteUnauthorized
*/
type GetCurrentUserInviteUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetCurrentUserInviteUnauthorized creates GetCurrentUserInviteUnauthorized with default headers values
func NewGetCurrentUserInviteUnauthorized() *GetCurrentUserInviteUnauthorized {

	return &GetCurrentUserInviteUnauthorized{}
}

// WithPayload adds the payload to the get current user invite unauthorized response
func (o *GetCurrentUserInviteUnauthorized) WithPayload(payload *modelapi.Error) *GetCurrentUserInviteUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user invite unauthorized response
func (o *GetCurrentUserInviteUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserInviteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
