// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// InitializeGroupBackupHandlerFunc turns a function with the right signature into a initialize group backup handler
type InitializeGroupBackupHandlerFunc func(InitializeGroupBackupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn InitializeGroupBackupHandlerFunc) Handle(params InitializeGroupBackupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// InitializeGroupBackupHandler interface for that can handle valid initialize group backup params
type InitializeGroupBackupHandler interface {
	Handle(InitializeGroupBackupParams, interface{}) middleware.Responder
}

// NewInitializeGroupBackup creates a new http.Handler for the initialize group backup operation
func NewInitializeGroupBackup(ctx *middleware.Context, handler InitializeGroupBackupHandler) *InitializeGroupBackup {
	return &InitializeGroupBackup{Context: ctx, Handler: handler}
}

/* InitializeGroupBackup swagger:route POST /users/current/computer/current/groups/{group_id}/backups backup initializeGroupBackup

Initialize a new backup

*/
type InitializeGroupBackup struct {
	Context *middleware.Context
	Handler InitializeGroupBackupHandler
}

func (o *InitializeGroupBackup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInitializeGroupBackupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
