// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/models"
)

// UploadBackupOKCode is the HTTP code returned for type UploadBackupOK
const UploadBackupOKCode int = 200

/*UploadBackupOK The updated backup object.

swagger:response uploadBackupOK
*/
type UploadBackupOK struct {

	/*
	  In: Body
	*/
	Payload *models.Backup `json:"body,omitempty"`
}

// NewUploadBackupOK creates UploadBackupOK with default headers values
func NewUploadBackupOK() *UploadBackupOK {

	return &UploadBackupOK{}
}

// WithPayload adds the payload to the upload backup o k response
func (o *UploadBackupOK) WithPayload(payload *models.Backup) *UploadBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload backup o k response
func (o *UploadBackupOK) SetPayload(payload *models.Backup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UploadBackupUnauthorizedCode is the HTTP code returned for type UploadBackupUnauthorized
const UploadBackupUnauthorizedCode int = 401

/*UploadBackupUnauthorized Unauthorized.

swagger:response uploadBackupUnauthorized
*/
type UploadBackupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadBackupUnauthorized creates UploadBackupUnauthorized with default headers values
func NewUploadBackupUnauthorized() *UploadBackupUnauthorized {

	return &UploadBackupUnauthorized{}
}

// WithPayload adds the payload to the upload backup unauthorized response
func (o *UploadBackupUnauthorized) WithPayload(payload *models.Error) *UploadBackupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload backup unauthorized response
func (o *UploadBackupUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadBackupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UploadBackupNotFoundCode is the HTTP code returned for type UploadBackupNotFound
const UploadBackupNotFoundCode int = 404

/*UploadBackupNotFound The specified resource was not found.

swagger:response uploadBackupNotFound
*/
type UploadBackupNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadBackupNotFound creates UploadBackupNotFound with default headers values
func NewUploadBackupNotFound() *UploadBackupNotFound {

	return &UploadBackupNotFound{}
}

// WithPayload adds the payload to the upload backup not found response
func (o *UploadBackupNotFound) WithPayload(payload *models.Error) *UploadBackupNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload backup not found response
func (o *UploadBackupNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadBackupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
