// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DownloadBackupHandlerFunc turns a function with the right signature into a download backup handler
type DownloadBackupHandlerFunc func(DownloadBackupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadBackupHandlerFunc) Handle(params DownloadBackupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DownloadBackupHandler interface for that can handle valid download backup params
type DownloadBackupHandler interface {
	Handle(DownloadBackupParams, interface{}) middleware.Responder
}

// NewDownloadBackup creates a new http.Handler for the download backup operation
func NewDownloadBackup(ctx *middleware.Context, handler DownloadBackupHandler) *DownloadBackup {
	return &DownloadBackup{Context: ctx, Handler: handler}
}

/* DownloadBackup swagger:route GET /users/current/computer/current/groups/{group_id}/backups/{backup_id}/download backup downloadBackup

Download the backup file

*/
type DownloadBackup struct {
	Context *middleware.Context
	Handler DownloadBackupHandler
}

func (o *DownloadBackup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadBackupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
