// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGroupBackupsHandlerFunc turns a function with the right signature into a get group backups handler
type GetGroupBackupsHandlerFunc func(GetGroupBackupsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGroupBackupsHandlerFunc) Handle(params GetGroupBackupsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGroupBackupsHandler interface for that can handle valid get group backups params
type GetGroupBackupsHandler interface {
	Handle(GetGroupBackupsParams, interface{}) middleware.Responder
}

// NewGetGroupBackups creates a new http.Handler for the get group backups operation
func NewGetGroupBackups(ctx *middleware.Context, handler GetGroupBackupsHandler) *GetGroupBackups {
	return &GetGroupBackups{Context: ctx, Handler: handler}
}

/* GetGroupBackups swagger:route GET /users/current/computer/current/groups/{group_id}/backups backup getGroupBackups

Get group backups

*/
type GetGroupBackups struct {
	Context *middleware.Context
	Handler GetGroupBackupsHandler
}

func (o *GetGroupBackups) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGroupBackupsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
