// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetGroupBackupOKCode is the HTTP code returned for type GetGroupBackupOK
const GetGroupBackupOKCode int = 200

/*GetGroupBackupOK The specified .

swagger:response getGroupBackupOK
*/
type GetGroupBackupOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Backup `json:"body,omitempty"`
}

// NewGetGroupBackupOK creates GetGroupBackupOK with default headers values
func NewGetGroupBackupOK() *GetGroupBackupOK {

	return &GetGroupBackupOK{}
}

// WithPayload adds the payload to the get group backup o k response
func (o *GetGroupBackupOK) WithPayload(payload *modelapi.Backup) *GetGroupBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group backup o k response
func (o *GetGroupBackupOK) SetPayload(payload *modelapi.Backup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupBackupUnauthorizedCode is the HTTP code returned for type GetGroupBackupUnauthorized
const GetGroupBackupUnauthorizedCode int = 401

/*GetGroupBackupUnauthorized Unauthorized.

swagger:response getGroupBackupUnauthorized
*/
type GetGroupBackupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupBackupUnauthorized creates GetGroupBackupUnauthorized with default headers values
func NewGetGroupBackupUnauthorized() *GetGroupBackupUnauthorized {

	return &GetGroupBackupUnauthorized{}
}

// WithPayload adds the payload to the get group backup unauthorized response
func (o *GetGroupBackupUnauthorized) WithPayload(payload *modelapi.Error) *GetGroupBackupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group backup unauthorized response
func (o *GetGroupBackupUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupBackupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupBackupNotFoundCode is the HTTP code returned for type GetGroupBackupNotFound
const GetGroupBackupNotFoundCode int = 404

/*GetGroupBackupNotFound The specified resource was not found.

swagger:response getGroupBackupNotFound
*/
type GetGroupBackupNotFound struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupBackupNotFound creates GetGroupBackupNotFound with default headers values
func NewGetGroupBackupNotFound() *GetGroupBackupNotFound {

	return &GetGroupBackupNotFound{}
}

// WithPayload adds the payload to the get group backup not found response
func (o *GetGroupBackupNotFound) WithPayload(payload *modelapi.Error) *GetGroupBackupNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group backup not found response
func (o *GetGroupBackupNotFound) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupBackupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupBackupInternalServerErrorCode is the HTTP code returned for type GetGroupBackupInternalServerError
const GetGroupBackupInternalServerErrorCode int = 500

/*GetGroupBackupInternalServerError Internal server error.

swagger:response getGroupBackupInternalServerError
*/
type GetGroupBackupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetGroupBackupInternalServerError creates GetGroupBackupInternalServerError with default headers values
func NewGetGroupBackupInternalServerError() *GetGroupBackupInternalServerError {

	return &GetGroupBackupInternalServerError{}
}

// WithPayload adds the payload to the get group backup internal server error response
func (o *GetGroupBackupInternalServerError) WithPayload(payload *modelapi.Error) *GetGroupBackupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group backup internal server error response
func (o *GetGroupBackupInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupBackupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
