// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// InitializeGroupBackupOKCode is the HTTP code returned for type InitializeGroupBackupOK
const InitializeGroupBackupOKCode int = 200

/*InitializeGroupBackupOK Newly created backup object.

swagger:response initializeGroupBackupOK
*/
type InitializeGroupBackupOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Backup `json:"body,omitempty"`
}

// NewInitializeGroupBackupOK creates InitializeGroupBackupOK with default headers values
func NewInitializeGroupBackupOK() *InitializeGroupBackupOK {

	return &InitializeGroupBackupOK{}
}

// WithPayload adds the payload to the initialize group backup o k response
func (o *InitializeGroupBackupOK) WithPayload(payload *modelapi.Backup) *InitializeGroupBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initialize group backup o k response
func (o *InitializeGroupBackupOK) SetPayload(payload *modelapi.Backup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitializeGroupBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InitializeGroupBackupBadRequestCode is the HTTP code returned for type InitializeGroupBackupBadRequest
const InitializeGroupBackupBadRequestCode int = 400

/*InitializeGroupBackupBadRequest If the backup is too big or there is any other problem.

swagger:response initializeGroupBackupBadRequest
*/
type InitializeGroupBackupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewInitializeGroupBackupBadRequest creates InitializeGroupBackupBadRequest with default headers values
func NewInitializeGroupBackupBadRequest() *InitializeGroupBackupBadRequest {

	return &InitializeGroupBackupBadRequest{}
}

// WithPayload adds the payload to the initialize group backup bad request response
func (o *InitializeGroupBackupBadRequest) WithPayload(payload *modelapi.Error) *InitializeGroupBackupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initialize group backup bad request response
func (o *InitializeGroupBackupBadRequest) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitializeGroupBackupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InitializeGroupBackupUnauthorizedCode is the HTTP code returned for type InitializeGroupBackupUnauthorized
const InitializeGroupBackupUnauthorizedCode int = 401

/*InitializeGroupBackupUnauthorized Unauthorized.

swagger:response initializeGroupBackupUnauthorized
*/
type InitializeGroupBackupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewInitializeGroupBackupUnauthorized creates InitializeGroupBackupUnauthorized with default headers values
func NewInitializeGroupBackupUnauthorized() *InitializeGroupBackupUnauthorized {

	return &InitializeGroupBackupUnauthorized{}
}

// WithPayload adds the payload to the initialize group backup unauthorized response
func (o *InitializeGroupBackupUnauthorized) WithPayload(payload *modelapi.Error) *InitializeGroupBackupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initialize group backup unauthorized response
func (o *InitializeGroupBackupUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitializeGroupBackupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InitializeGroupBackupInternalServerErrorCode is the HTTP code returned for type InitializeGroupBackupInternalServerError
const InitializeGroupBackupInternalServerErrorCode int = 500

/*InitializeGroupBackupInternalServerError Internal server error.

swagger:response initializeGroupBackupInternalServerError
*/
type InitializeGroupBackupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewInitializeGroupBackupInternalServerError creates InitializeGroupBackupInternalServerError with default headers values
func NewInitializeGroupBackupInternalServerError() *InitializeGroupBackupInternalServerError {

	return &InitializeGroupBackupInternalServerError{}
}

// WithPayload adds the payload to the initialize group backup internal server error response
func (o *InitializeGroupBackupInternalServerError) WithPayload(payload *modelapi.Error) *InitializeGroupBackupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initialize group backup internal server error response
func (o *InitializeGroupBackupInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitializeGroupBackupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
