// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// LogComputerBackupOKCode is the HTTP code returned for type LogComputerBackupOK
const LogComputerBackupOKCode int = 200

/*LogComputerBackupOK The logged computer backup object

swagger:response logComputerBackupOK
*/
type LogComputerBackupOK struct {

	/*
	  In: Body
	*/
	Payload *modelapi.GroupComputerBackup `json:"body,omitempty"`
}

// NewLogComputerBackupOK creates LogComputerBackupOK with default headers values
func NewLogComputerBackupOK() *LogComputerBackupOK {

	return &LogComputerBackupOK{}
}

// WithPayload adds the payload to the log computer backup o k response
func (o *LogComputerBackupOK) WithPayload(payload *modelapi.GroupComputerBackup) *LogComputerBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the log computer backup o k response
func (o *LogComputerBackupOK) SetPayload(payload *modelapi.GroupComputerBackup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogComputerBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogComputerBackupBadRequestCode is the HTTP code returned for type LogComputerBackupBadRequest
const LogComputerBackupBadRequestCode int = 400

/*LogComputerBackupBadRequest Supplied parameters were not okay.

swagger:response logComputerBackupBadRequest
*/
type LogComputerBackupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewLogComputerBackupBadRequest creates LogComputerBackupBadRequest with default headers values
func NewLogComputerBackupBadRequest() *LogComputerBackupBadRequest {

	return &LogComputerBackupBadRequest{}
}

// WithPayload adds the payload to the log computer backup bad request response
func (o *LogComputerBackupBadRequest) WithPayload(payload *modelapi.Error) *LogComputerBackupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the log computer backup bad request response
func (o *LogComputerBackupBadRequest) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogComputerBackupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogComputerBackupUnauthorizedCode is the HTTP code returned for type LogComputerBackupUnauthorized
const LogComputerBackupUnauthorizedCode int = 401

/*LogComputerBackupUnauthorized Unauthorized.

swagger:response logComputerBackupUnauthorized
*/
type LogComputerBackupUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewLogComputerBackupUnauthorized creates LogComputerBackupUnauthorized with default headers values
func NewLogComputerBackupUnauthorized() *LogComputerBackupUnauthorized {

	return &LogComputerBackupUnauthorized{}
}

// WithPayload adds the payload to the log computer backup unauthorized response
func (o *LogComputerBackupUnauthorized) WithPayload(payload *modelapi.Error) *LogComputerBackupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the log computer backup unauthorized response
func (o *LogComputerBackupUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogComputerBackupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogComputerBackupInternalServerErrorCode is the HTTP code returned for type LogComputerBackupInternalServerError
const LogComputerBackupInternalServerErrorCode int = 500

/*LogComputerBackupInternalServerError Internal server error.

swagger:response logComputerBackupInternalServerError
*/
type LogComputerBackupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewLogComputerBackupInternalServerError creates LogComputerBackupInternalServerError with default headers values
func NewLogComputerBackupInternalServerError() *LogComputerBackupInternalServerError {

	return &LogComputerBackupInternalServerError{}
}

// WithPayload adds the payload to the log computer backup internal server error response
func (o *LogComputerBackupInternalServerError) WithPayload(payload *modelapi.Error) *LogComputerBackupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the log computer backup internal server error response
func (o *LogComputerBackupInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogComputerBackupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
