// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LogComputerBackupHandlerFunc turns a function with the right signature into a log computer backup handler
type LogComputerBackupHandlerFunc func(LogComputerBackupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn LogComputerBackupHandlerFunc) Handle(params LogComputerBackupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// LogComputerBackupHandler interface for that can handle valid log computer backup params
type LogComputerBackupHandler interface {
	Handle(LogComputerBackupParams, interface{}) middleware.Responder
}

// NewLogComputerBackup creates a new http.Handler for the log computer backup operation
func NewLogComputerBackup(ctx *middleware.Context, handler LogComputerBackupHandler) *LogComputerBackup {
	return &LogComputerBackup{Context: ctx, Handler: handler}
}

/* LogComputerBackup swagger:route POST /users/current/computers/current/groups/{group_id}/backups/{backup_id}/log backup logComputerBackup

Log the local computer backup

*/
type LogComputerBackup struct {
	Context *middleware.Context
	Handler LogComputerBackupHandler
}

func (o *LogComputerBackup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLogComputerBackupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
