// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RequestBackupUploadHandlerFunc turns a function with the right signature into a request backup upload handler
type RequestBackupUploadHandlerFunc func(RequestBackupUploadParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RequestBackupUploadHandlerFunc) Handle(params RequestBackupUploadParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RequestBackupUploadHandler interface for that can handle valid request backup upload params
type RequestBackupUploadHandler interface {
	Handle(RequestBackupUploadParams, interface{}) middleware.Responder
}

// NewRequestBackupUpload creates a new http.Handler for the request backup upload operation
func NewRequestBackupUpload(ctx *middleware.Context, handler RequestBackupUploadHandler) *RequestBackupUpload {
	return &RequestBackupUpload{Context: ctx, Handler: handler}
}

/* RequestBackupUpload swagger:route PUT /users/current/computer/current/groups/{group_id}/backups/{backup_id} backup requestBackupUpload

Update the upload request flag

*/
type RequestBackupUpload struct {
	Context *middleware.Context
	Handler RequestBackupUploadHandler
}

func (o *RequestBackupUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRequestBackupUploadParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
