// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadBackupHandlerFunc turns a function with the right signature into a upload backup handler
type UploadBackupHandlerFunc func(UploadBackupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadBackupHandlerFunc) Handle(params UploadBackupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UploadBackupHandler interface for that can handle valid upload backup params
type UploadBackupHandler interface {
	Handle(UploadBackupParams, interface{}) middleware.Responder
}

// NewUploadBackup creates a new http.Handler for the upload backup operation
func NewUploadBackup(ctx *middleware.Context, handler UploadBackupHandler) *UploadBackup {
	return &UploadBackup{Context: ctx, Handler: handler}
}

/* UploadBackup swagger:route POST /users/current/computers/current/groups/{group_id}/backups/{backup_id}/upload backup uploadBackup

Upload the backup file

*/
type UploadBackup struct {
	Context *middleware.Context
	Handler UploadBackupHandler
}

func (o *UploadBackup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUploadBackupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
