// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mnimidamonbackend/adapter/restapi/modelapi"
)

// GetCurrentUserInvitesOKCode is the HTTP code returned for type GetCurrentUserInvitesOK
const GetCurrentUserInvitesOKCode int = 200

/*GetCurrentUserInvitesOK Array of current user active group invites.

swagger:response getCurrentUserInvitesOK
*/
type GetCurrentUserInvitesOK struct {

	/*
	  In: Body
	*/
	Payload []*modelapi.Invite `json:"body,omitempty"`
}

// NewGetCurrentUserInvitesOK creates GetCurrentUserInvitesOK with default headers values
func NewGetCurrentUserInvitesOK() *GetCurrentUserInvitesOK {

	return &GetCurrentUserInvitesOK{}
}

// WithPayload adds the payload to the get current user invites o k response
func (o *GetCurrentUserInvitesOK) WithPayload(payload []*modelapi.Invite) *GetCurrentUserInvitesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user invites o k response
func (o *GetCurrentUserInvitesOK) SetPayload(payload []*modelapi.Invite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserInvitesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*modelapi.Invite, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCurrentUserInvitesUnauthorizedCode is the HTTP code returned for type GetCurrentUserInvitesUnauthorized
const GetCurrentUserInvitesUnauthorizedCode int = 401

/*GetCurrentUserInvitesUnauthorized Unauthorized.

swagger:response getCurrentUserInvitesUnauthorized
*/
type GetCurrentUserInvitesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetCurrentUserInvitesUnauthorized creates GetCurrentUserInvitesUnauthorized with default headers values
func NewGetCurrentUserInvitesUnauthorized() *GetCurrentUserInvitesUnauthorized {

	return &GetCurrentUserInvitesUnauthorized{}
}

// WithPayload adds the payload to the get current user invites unauthorized response
func (o *GetCurrentUserInvitesUnauthorized) WithPayload(payload *modelapi.Error) *GetCurrentUserInvitesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user invites unauthorized response
func (o *GetCurrentUserInvitesUnauthorized) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserInvitesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCurrentUserInvitesInternalServerErrorCode is the HTTP code returned for type GetCurrentUserInvitesInternalServerError
const GetCurrentUserInvitesInternalServerErrorCode int = 500

/*GetCurrentUserInvitesInternalServerError Internal server error.

swagger:response getCurrentUserInvitesInternalServerError
*/
type GetCurrentUserInvitesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *modelapi.Error `json:"body,omitempty"`
}

// NewGetCurrentUserInvitesInternalServerError creates GetCurrentUserInvitesInternalServerError with default headers values
func NewGetCurrentUserInvitesInternalServerError() *GetCurrentUserInvitesInternalServerError {

	return &GetCurrentUserInvitesInternalServerError{}
}

// WithPayload adds the payload to the get current user invites internal server error response
func (o *GetCurrentUserInvitesInternalServerError) WithPayload(payload *modelapi.Error) *GetCurrentUserInvitesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get current user invites internal server error response
func (o *GetCurrentUserInvitesInternalServerError) SetPayload(payload *modelapi.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCurrentUserInvitesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
