// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCurrentUserGroupsHandlerFunc turns a function with the right signature into a get current user groups handler
type GetCurrentUserGroupsHandlerFunc func(GetCurrentUserGroupsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCurrentUserGroupsHandlerFunc) Handle(params GetCurrentUserGroupsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCurrentUserGroupsHandler interface for that can handle valid get current user groups params
type GetCurrentUserGroupsHandler interface {
	Handle(GetCurrentUserGroupsParams, interface{}) middleware.Responder
}

// NewGetCurrentUserGroups creates a new http.Handler for the get current user groups operation
func NewGetCurrentUserGroups(ctx *middleware.Context, handler GetCurrentUserGroupsHandler) *GetCurrentUserGroups {
	return &GetCurrentUserGroups{Context: ctx, Handler: handler}
}

/* GetCurrentUserGroups swagger:route GET /users/current/groups current user getCurrentUserGroups

Get current user groups

*/
type GetCurrentUserGroups struct {
	Context *middleware.Context
	Handler GetCurrentUserGroupsHandler
}

func (o *GetCurrentUserGroups) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCurrentUserGroupsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
